### ISSUE TITLE
Proposal for higher level language

### ISSUE THREAD

**Issue by kristianmandrup** [eldh/simple-reason-react#3]
I think we need to move beyond low level languages for React. Why not experiment with higher level languages that compile to Reason using f.ex bs-react conventions ;)

http://createyourproglang.com/

Parser generators:
- https://nearley.js.org/
- https://sap.github.io/chevrotain/docs/
- https://matklad.github.io/2018/06/06/modern-parser-generator.html
- https://github.com/matklad/fall/

Proposed example of higher level language that should result in the sample code in the Readme

```
component Counter {
  props {
    initial#int = 0
  },
  states {
    count: {
      initial, value: count#int, action: setCount
    }
  },
  triggers {
    increase: setCount(count + 1)
  },
  render {
    div {
      {count},
      button {
        @click => increase,
        "click me"
      }
    }
  }
}
```

Ideally perhaps (optionally?) using a Python like indentation syntax to further reduce the "fluff"

```
component Counter
  props: 
    initial#int = 0
  states:
    count:
      initial 
      value: count#int
      action: setCount
  triggers:
    increase: setCount(count + 1)
  render:
    div 
      {count}
      button 
        @click => increase
        "click me"
```

Output:

```reason
module Counter = {
  let component = ReasonReact.component("Counter");

  let make = (~initial=0, _children) => {
    ...component,
    render: _self => {
      let (count, setCount) = ReactHooks.useState(initial);
      <div>
        {ReasonReact.string(string_of_int(count))}
        <button onClick={_ => setCount(. count + 1)}>
          {ReasonReact.string("Click me")}
        </button>
      </div>;
    },
  };
};
```

I'd love to get your thoughts on this. Cheers

**Comment by eldh** [comment]
That looks really cool, and I'm sure something like that would be really nice. For `BsReact` I want to keep as close to vanilla react as possible though, to reduce complexity and to keep it approachable for people coming from JS.

One thing I'd love to see though is some way to enforce the rules of hooks on a language level (as I understand they're basically algebraic effects) but I wouldn't really know how to do that.

I'll close this issue as it's not really actionable atm, but It's still an interesting discussion!
